name: Trigger auto deployment for runner-functions-nightly55

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/runner-functions-nightly55-AutoDeployTrigger-6c584894-0061-4f4c-b8ba-bbd50d46737b.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: swiftfiddle.azurecr.io
          username: ${{ secrets.RUNNERFUNCTIONSNIGHTLY55_REGISTRY_USERNAME }}
          password: ${{ secrets.RUNNERFUNCTIONSNIGHTLY55_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: swiftfiddle.azurecr.io/runner-functions-nightly55:latest
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RUNNERFUNCTIONSNIGHTLY55_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n runner-functions-nightly55 -g swiftfiddle --server swiftfiddle.azurecr.io --username  ${{ secrets.RUNNERFUNCTIONSNIGHTLY55_REGISTRY_USERNAME }} --password ${{ secrets.RUNNERFUNCTIONSNIGHTLY55_REGISTRY_PASSWORD }}
            az containerapp update -n runner-functions-nightly55 -g swiftfiddle --image swiftfiddle.azurecr.io/runner-functions-nightly55:latest
